name: Docker Build

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rafafrassetto/strapi-cms:latest
          build-args: |
            APP_KEYS=${{ secrets.APP_KEYS }}
            ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}
            API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}
            TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}