name: Publicar Imagem HTML Docker

on:
  push:
    branches:
      - master

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Construir e Publicar a Imagem Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/html-app:latest

    - name: Imagem Publicada
      run: echo "Imagem Docker ${{ secrets.DOCKER_HUB_USERNAME }}/html-app:latest publicada com sucesso!"