name: PR Tests
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install npm dependencies (for Playwright)
      # dependências do Strapi serão instaladas no Dockerfile.
      run: npm install --prefix ./e2e-tests

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Build Strapi Docker image for testing
      # constrói a imagem Docker localmente sem fazer push para o Docker Hub,
      run: docker build -t strapi-cms-test:${{ github.sha }} .

    - name: Run Strapi Docker container
      run: docker run -p 1337:1337 --name strapi-test -d strapi-cms-test:${{ github.sha }}

    - name: Wait for Strapi to be ready
      run: |
        echo "Waiting for Strapi to be ready on http://localhost:1337..."
        for i in $(seq 1 30); do
          if curl -s http://localhost:1337/admin > /dev/null; then
            echo "Strapi is ready!"
            exit 0
          fi
          echo "Still waiting... ($i/30)"
          sleep 5
        done
        echo "Strapi did not become ready in time."
        exit 1 # Falha se o Strapi não ficar pronto

    - name: Run Playwright tests
      run: npm run test:e2e --prefix ./e2e-tests
      env:
        CI: true

    - name: Stop and remove Strapi container
      if: always()
      run: docker stop strapi-test && docker rm strapi-test
