name: Terraform Deploy

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.x.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform
        run: terraform plan -no-color -var="docker_image=rafafrassetto/strapi-cms:latest"

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        working-directory: ./terraform
        run: terraform apply -auto-approve -var="docker_image=rafafrassetto/strapi-cms:latest"