name: Terraform Deploy
on:
  push:
    branches: [master]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init
      
    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var="docker_image=rafafrassetto/strapi-cms:latest"
      env:
        TF_VAR_docker_image: rafafrassetto/strapi-cms:latest
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}